/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Loïc Norgeot (https://sketchfab.com/norgeotloic)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mosquito-in-amber-53a61d58c09b4d2ab30e269aa3e22078
Title: Mosquito in amber
*/

import { useGLTF } from "@react-three/drei";
import { GroupProps } from "@react-three/fiber";

export function MosquitoInAmber(props: GroupProps) {
  const model = useGLTF("models/mosquito_in_amber/scene.gltf");
  console.log(model);
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={(model.nodes["5_amber_lr_PBR_0"] as any).geometry}
        material={model.materials.material}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={(model.nodes["6_eclats_eclats_0"] as any).geometry}
        material={model.materials.eclats}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={
          (model.nodes["2_mosquito_lr_originalo_material_0_0"] as any).geometry
        }
        material={model.materials["original.o_material_0"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("models/mosquito_in_amber/scene.gltf");
